Xbox workaround 2
SutandoTsukai181/RyuModManager pull request #18
Opened 2022-09-27 17:27 UTC by hvhbot

#17

2022-09-28 01:17 UTC, KaylinOwO commented
yakuza hvh

2022-09-28 14:49 UTC, SutandoTsukai181 commented on Utils/GamePath.cs
> +            return path.Contains("\\Content\\");
This will only work on Windows. Maybe make it use `Path.DirectorySeparatorChar` instead of a hardcoded `\\`

2022-09-28 14:50 UTC, SutandoTsukai181 requested changes
Please address the changes requested.

2022-09-29 03:41 UTC, SutandoTsukai181 commented on Utils/GamePath.cs
> +            return path.Contains("\\Content\\");
That's unrelated to whether RMM can process the paths correctly or not. RMM should work regardless of the OS you run it on. Please use `DirectorySeparatorChar` instead. Besides, having hardcoded windows-style path separators is not a good idea.

2022-09-30 15:33 UTC, SutandoTsukai181 approved these changes

2022-11-08 04:28 UTC, merged